title: shellspec
description: BDD style unit testing framework for POSIX compatible shell script
theme: jekyll-theme-slate
github:
  repository_url: https://github.com/shellspec/shellspec
google_analytics: UA-50458188-3
url: https://shellspec.info
plugins:
  - jekyll-sitemap
