title: ShellSpec
description: BDD unit testing framework for bash, zsh, dash and all POSIX shell scripts with coverage reporting
theme: jekyll-theme-slate
github:
  repository_url: https://github.com/shellspec/shellspec
google_analytics: UA-50458188-3
url: https://shellspec.info
plugins:
  - jekyll-sitemap
