title: ShellSpec
tagline: BDD unit testing framework for shell scripts
description: A full-featured BDD unit testing framework for bash, ksh, zsh, dash and all POSIX shells that provides first-class features such as code coverage, mocking, parallel execution, parameterized testing and more
theme: jekyll-theme-slate
github:
  repository_url: https://github.com/shellspec/shellspec
google_analytics: UA-50458188-3
url: https://shellspec.info
plugins:
  - jekyll-sitemap
